site_name: 社会实践平台
site_author: jch #作者名

nav:
  - 主页:
    - home: index.md
    - Recruit: home/Recruit.md
    - Information: home/Information.md
  - 我们:
    - 关于我们: Update/need.md
theme:
  name: material
  # custom dir:overrides
  font:
    text: Bitter
  icon:
    logo: material/library-shelves
    admonition:
      <type>: material/file-alert-outline

  favicon: img/avatar.png
  # img/11.ico
  palette:
    #primary: blue grey

    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的accent:cyan
      accent: cyan # 链接等可交互元件的高亮色toggle:
      toggle:
        icon: material/weather-night #切换至夜间模式
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black # 上方的accent:cyan
      accent: cyan # 链接等可交互元件的高亮色toggle:
      toggle:
        icon: material/weather-sunny #切换至日间模式
        name: 切换至日间模式
  feathers:
    - navigation.instant #- header.auto hide #自动隐藏
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top #返回顶部的按钮在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand #打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - content.tabs.link
  language: zh # 一些提示性的文字会变成中文